### ISSUE TITLE
1.6.4 -> Crash

### ISSUE THREAD

**Issue by Kopla-BR** [nexusnode/CraftingDead-Files#1]
Used JAR: craftingdead-1.3.5_B2-1.6.4-obf.jar
JAR version: 1.3.5_B2
Game version: 1.6.4

Error description: "Exception in server tick loop"
Null Pointer Exception error in class  TcpClient extends >> **NetworkService** << <Bootstrap, Channel>:
(java.lang.NullPointerException
    at com.craftingdead.network.b.a(Unknown Source)
    at com.craftingdead.CraftingDead.a(Unknown Source)
    at com.craftingdead.b.a(Unknown Source)
    at com.craftingdead.b.tickEnd(Unknown Source)
    at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
    at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:150)
    at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:285)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:820)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665)
    at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583))

**Comment by Kopla-BR** [comment]
@Brad-Hunter
